{
 "title": "Top N Usage Report",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Esx Host Cpu Usage",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$tag_esxhostname",
     "groupBy": [
      { "params": [ "esxhostname" ], "type": "tag" }
     ],
     "measurement": "vsphere_host_cpu",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Esx Host Memory Usage",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "alias": "$tag_esxhostname",
     "groupBy": [
      { "params": [ "esxhostname" ], "type": "tag" }
     ],
     "measurement": "vsphere_host_mem",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Guest vCpu Usage",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 10, "y": 0 },
   "targets": [
    {
     "alias": "$tag_vmname",
     "groupBy": [
      { "params": [ "vmname" ], "type": "tag" }
     ],
     "measurement": "vsphere_vm_cpu",
     "query": "SELECT last(\"usage_average\") FROM \"vsphere_vm_cpu\" WHERE $timeFilter GROUP BY \"vmname\"",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Guest vMemory Usage",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 14, "y": 0 },
   "targets": [
    {
     "alias": "$tag_vmname",
     "groupBy": [
      { "params": [ "vmname" ], "type": "tag" }
     ],
     "measurement": "vsphere_vm_mem",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vm Write IOPs",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 18, "y": 0 },
   "targets": [
    {
     "alias": "$tag_vmname $tag_disk",
     "groupBy": [
      { "params": [ "vmname" ], "type": "tag" },
      { "params": [ "disk" ], "type": "tag" }
     ],
     "measurement": "vsphere_vm_virtualDisk",
     "select": [
      [
       { "params": [ "numberWriteAveraged_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Esx Host Network Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "alias": "$tag_source",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" }
     ],
     "measurement": "vsphere_host_net",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Vm Read IOPs",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 18, "y": 12 },
   "targets": [
    {
     "alias": "$tag_vmname $tag_disk",
     "groupBy": [
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "vmname" ], "type": "tag" }
     ],
     "measurement": "vsphere_vm_virtualDisk",
     "select": [
      [
       { "params": [ "numberReadAveraged_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}